FROM node:lts-alpine
# set working directory
WORKDIR /usr/src/binapi-ui
# add `/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/binapi-ui/node_modules/.bin:$PATH
# copy files in
COPY package*.json /usr/src/binapi-ui/
# install and cache app dependencies
RUN npm install --location=global @angular/cli
# RUN npm install --location=global @angular/cli @angular-devkit/build-angular && npm install --dev --legacy-peer-deps
RUN npm install --dev --legacy-peer-deps
# expose 4200
EXPOSE 4200
# run the app
CMD ["npm", "start"]